### ISSUE TITLE
Build Failed on 12.0-RELEASE

### ISSUE THREAD

**Issue by yzgyyang** [prash-wghats/VSCode-For-FreeBSD#23]
```
+ script/build -c static_library -t x64
ninja: Entering directory `src/out-x64/static_library'
[4779/15783] CC obj/third_party/freetype/freetype/autofit.o
FAILED: obj/third_party/freetype/freetype/autofit.o 
clang40 -MMD -MF obj/third_party/freetype/freetype/autofit.o.d -DPDFIUM_REQUIRED_MODULES -DFT2_BUILD_LIBRARY -DDARWIN_NO_CARBON -DFT_CONFIG_MODULES_H=\"freetype-custom-config/ftmodule.h\" -DFT_CONFIG_OPTIONS_H=\"freetype-custom-config/ftoption.h\" -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DCR_CLANG_REVISION=\"307486-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/freetype/include -I../../third_party/freetype/src/include -Igen/shim_headers/harfbuzz_shim -I../../third_party/libpng -I../../third_party/zlib -I/usr/local/include/harfbuzz -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-user-defined-warnings -Wno-unused-function  -c ../../third_party/freetype/src/src/autofit/autofit.c -o obj/third_party/freetype/freetype/autofit.o
In file included from ../../third_party/freetype/src/src/autofit/autofit.c:35:
../../third_party/freetype/src/src/autofit/afshaper.c:140:5: error: 'hb_ot_tags_from_script' is deprecated [-Werror,-Wdeprecated-declarations]
    hb_ot_tags_from_script( script,
    ^
/usr/local/include/harfbuzz/hb-deprecated.h:236:1: note: 'hb_ot_tags_from_script' has been explicitly marked deprecated here
hb_ot_tags_from_script (hb_script_t  script,
^
1 error generated.
[4781/15783] CC obj/third_party/freetype/freetype/ftstroke.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 96, in <module>
    sys.exit(main())
  File "script/build", line 70, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
$ 
```

```
uname -a
FreeBSD freebsd-vbox 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
```

**Comment by prash-wghats** [comment]
`/usr/local/include/harfbuzz/hb-deprecated.h:236:1:` . This is using the system harfbuzz instead of the one included in the chromium package. quick way to test is remove the system harbuzz or temporarily move it, and try compiling again
